using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using MyFirstApi.Models;
using MyFirstApi.Services.Interfaces;

namespace MyFirstApi.Services
{
    public class PdfService : IPdfService
    {
        public byte[] GenerateEmployeePdf(
            List<Employee> employees)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);

                    page.Header()
                        .Text("Employee List")
                        .FontSize(20)
                        .Bold();

                    page.Content()
                        .PaddingTop(20)
                        .Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.ConstantColumn(40);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("ID").Bold();
                                header.Cell().Text("Name").Bold();
                                header.Cell().Text("Email").Bold();
                                header.Cell().Text("Phone").Bold();
                                header.Cell().Text("Department").Bold();
                            });

                            foreach (var employee in employees)
                            {
                                table.Cell().Text(employee.Id.ToString());
                                table.Cell().Text(employee.Name);
                                table.Cell().Text(employee.Email);
                                table.Cell().Text(employee.Phone);
                                table.Cell().Text(employee.Department);
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by MyFirstApi");
                        });
                });
            });

            return document.GeneratePdf();
        }
    }
}